# monitoring/prometheus.yml
# Define how often Prometheus scrapes metrics and from where

# Set the global scrape interval for Prometheus
global:
  scrape_interval: 15s

# Define the targets to be scraped
scrape_configs:
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']

  - job_name: 'jenkins'
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['10.0.2.15:8080']

